# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: < SEED />
email: tonyxu82@gmail.com
description: Seed of Dream
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


github_username:  tonyxu82
twitter_username: tonytonyxu

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname: txtechnet

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
