# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: < SEED />
email: tonyxu82@gmail.com
description: Still other seed fell on good soil. It came up, grew and produced a crop, some multiplying thrity, some sixty, some a hundred times.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: tonytonyxu
github_username:  tonyxu82

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname: txtechnet

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
